AWSTemplateFormatVersion: "2010-09-09"

Description: Defines a subnet

Parameters:
  VpcId:
    Type: String
    Description: The ID of the VPC to add the subnet to

  AvailabilityZone:
    Type: Number
    Description: Zone Number

  PublicZone:
    Type: String
    Description: Is this a public subnet

  CidrBlock:
    Type: String
    Description: The CidrBlock of the Subnet
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

Conditions:
  IsPublicZone: !Equals
      - !Ref PublicZone
      - "true"

Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ !Ref AvailabilityZone, Fn::GetAZs: !Ref "AWS::Region" ]
      MapPublicIpOnLaunch: !Ref PublicZone
      CidrBlock: !Ref CidrBlock
      Tags:
        - Key: Name
          Value: 
            Fn::If:
              - IsPublicZone
              - !Sub 
                - "public-${AZ}"
                - { AZ: !Select [ !Ref AvailabilityZone, Fn::GetAZs: !Ref "AWS::Region" ]}
              - !Sub
                - "private-${AZ}"
                - { AZ: !Select [ !Ref AvailabilityZone, Fn::GetAZs: !Ref "AWS::Region" ]}

  SubnetParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !If [IsPublicZone, 
          !Sub "/cloudformation/vpc/az${AvailabilityZone}-public-subnet/id", 
          !Sub "/cloudformation/vpc/az${AvailabilityZone}-private-subnet/id"]
      Type: String
      Value: !Ref Subnet 

Outputs:
  SubnetId:
    Value: !Ref Subnet