AWSTemplateFormatVersion: "2010-09-09"

Description: Defines a transit gateway attachment

Parameters:
  VpcId:
    Type: String
    Description: The ID of the VPC to add the subnet to

  TransitGatewayId:
    Type: String
    Description: The id of the shared tgw

  SubnetIds:
    Type: CommaDelimitedList
    Description: List of subnet IDs to use with the transit gateway attachment

Resources:
  TgwAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: tgw-attachment
      TransitGatewayId: !Ref TransitGatewayId
      VpcId: !Ref VpcId