AWSTemplateFormatVersion: "2010-09-09"

Description: VPC Template

Parameters:
  VpcName:
    Type: String
    Description: Name of the VPC

  VpcCidr:
    Type: String
    Description: A network CIDR e.g. "10.0.0.0/16"
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: True
      EnableDnsHostnames: True
      InstanceTenancy: default
      CidrBlock: { Ref: VpcCidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Sub": "${VpcName}"

  VpcIdParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/cloudformation/vpc/id"
      Type: "String"
      Value: { Ref: Vpc }

Outputs:
  VpcId:
    Value: { Ref: Vpc }
